import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider";
import { CookiesProvider } from "next-client-cookies/server";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <CookiesProvider>
            <ReactQueryClientProvider>
                <html lang="en">
                    <body className={inter.className}>{children}</body>
                </html>
            </ReactQueryClientProvider>
        </CookiesProvider>
    );
}
